User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotification'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
User belongs to experiment group 'pythonRunFailedTestsButtonDisplayed'
User belongs to experiment group 'pythonRefreshTestsButtonDisplayed'
User belongs to experiment group 'pythonRememberDebugConfig'
Python interpreter path: /bin/python3
Starting Pylance language server.
Error 2021-10-08 17:45:52: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://ssh-remote+192.168.224.101/home/webalive/.config/Code/User/settings.json' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+192.168.224.101/home/webalive/.config/Code/User/settings.json')
	at _handleError (/home/webalive/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/out/vs/server/remoteExtensionHostProcess.js:94:160087)
	at async y.readText (/home/webalive/.vscode-server/extensions/ms-python.python-2021.9.1246542782/out/client/extension.js:9:314351)
	at async p.doesFileNeedToBeFixed (/home/webalive/.vscode-server/extensions/ms-python.python-2021.9.1246542782/out/client/extension.js:59:823969)
	at async /home/webalive/.vscode-server/extensions/ms-python.python-2021.9.1246542782/out/client/extension.js:59:823096
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/home/webalive/.vscode-server/extensions/ms-python.python-2021.9.1246542782/out/client/extension.js:59:823042)
	at async p.updateTestSettings (/home/webalive/.vscode-server/extensions/ms-python.python-2021.9.1246542782/out/client/extension.js:59:822669)] {
  code: 'FileNotFound'
}
> conda --version
Error 2021-10-08 19:04:49: Error while running worker[Worker 1]. undefined
Error 2021-10-08 19:04:49: Error while running worker[Worker 2]. undefined
